include: package:flutter_lints/flutter.yaml

linter:
  rules: # https://dart.dev/tools/linter-rules
    flutter_style_todos: true
    always_use_package_imports: true
    directives_ordering: true
    require_trailing_commas: true
    sort_constructors_first: true
    unawaited_futures: true

analyzer:
  errors:
    invalid_annotation_target: ignore