name: pokedex
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Dart version

dependencies:
  flutter:
    sdk: flutter

  # presentation
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.2
  
  # localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # router
  auto_route: ^8.2.0

  # model
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0

  # network
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # build runner
  build_runner: ^2.4.11

  # model
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  # router
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  generate: true